Call configure method of parent class.
8bcb1f8dafd overrides the configure method but this removes a number of
important bootstrapping steps like enabling environment variables in the
ssh session (for example, add_env_var stopped working because
`PermitUserEnvironment` is no longer added to sshd_config).

The platform of the nodeset generated in vagrant_spec had also needed to
be changed into an instance of Beaker::Platform to prevent the following
error:

  1) Beaker::Vagrant with options[:provision] = false calls #get_ip_from_vagrant_file
     Failure/Error: super

     NoMethodError:
       undefined method `to_array' for "unix":String
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/host/unix.rb:52:in `skip_set_env?'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/host_prebuilt_steps.rb:563:in `block in set_env'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:118:in `block in run_block_on'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:117:in `map'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:117:in `run_block_on'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/host_prebuilt_steps.rb:562:in `set_env'
     # ./.bundle/gems/beaker-3.37.0/lib/beaker/hypervisor.rb:106:in `configure'
     # ./lib/beaker/hypervisor/vagrant.rb:242:in `configure'
     # ./spec/beaker/hypervisor/vagrant_spec.rb:519:in `block (3 levels) in <module:Beaker>'